spring:
  datasource:
    username: root
    password: ssf123123
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
#整合mybatis最重要
mybatis:
  type-aliases-package: com.arctic.musicshop.pojo
  mapper-locations: classpath:Mybatis/Mapper/*.xml